"""initial_schema

Revision ID: e661b41bbda3
Revises: 
Create Date: 2026-08-06 15:58:55.160039

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661b41bbda3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_created_at'), 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_title')
    )
    op.create_index('ix_series_normalized_title', 'series', ['normalized_title'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_is_banned'), 'users', ['is_banned'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.BigInteger(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_users_user_id'), 'banned_users', ['user_id'], unique=False)
    op.create_table('file_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'COMING_SOON', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('admin_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_requests_status'), 'file_requests', ['status'], unique=False)
    op.create_index(op.f('ix_file_requests_user_id'), 'file_requests', ['user_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'season_number', name='uq_series_season_number')
    )
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('quality', sa.Enum('Q480P', 'Q720P', 'Q1080P', 'Q4K', 'SOURCE_UNKNOWN', name='qualityenum'), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'episode_number', 'quality', 'language', name='uq_episode_variant')
    )
    op.create_index(op.f('ix_episodes_episode_number'), 'episodes', ['episode_number'], unique=False)
    op.create_index(op.f('ix_episodes_file_hash'), 'episodes', ['file_hash'], unique=True)
    op.create_index(op.f('ix_episodes_is_active'), 'episodes', ['is_active'], unique=False)
    op.create_index(op.f('ix_episodes_quality'), 'episodes', ['quality'], unique=False)
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_quality'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_is_active'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_file_hash'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_episode_number'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_file_requests_user_id'), table_name='file_requests')
    op.drop_index(op.f('ix_file_requests_status'), table_name='file_requests')
    op.drop_table('file_requests')
    op.drop_index(op.f('ix_banned_users_user_id'), table_name='banned_users')
    op.drop_table('banned_users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_banned'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_series_normalized_title', table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_created_at'), table_name='search_logs')
    op.drop_table('search_logs')
    # ### end Alembic commands ###
