"""add 1440p to qualityenum

Revision ID: 4a655dd692d1
Revises: 511b6917c651
Create Date: 2026-08-06 19:24:36.278370

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a655dd692d1'
down_revision: Union[str, None] = '511b6917c651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE qualityenum ADD VALUE IF NOT EXISTS '1440p'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
