"""drop uq_episode_variant

Revision ID: a1b2c3d4e5f6
Revises: 8aba2c1d21dd
Create Date: 2026-08-10 16:56:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '8aba2c1d21dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_episode_variant', 'episodes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_episode_variant', 'episodes', ['season_id', 'episode_number', 'quality', 'language'])
    # ### end Alembic commands ###
