"""Add ban_reason to User

Revision ID: 8aba2c1d21dd
Revises: 4a655dd692d1
Create Date: 2026-08-08 23:59:15.572549

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aba2c1d21dd'
down_revision: Union[str, None] = '4a655dd692d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    # ### end Alembic commands ###
