"""add raw_filename to episode

Revision ID: 511b6917c651
Revises: e661b41bbda3
Create Date: 2026-08-06 17:52:18.642065

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511b6917c651'
down_revision: Union[str, None] = 'e661b41bbda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('raw_filename', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'raw_filename')
    # ### end Alembic commands ###
